-- https://github.com/microsoft/vscode/blob/main/src/vs/base/common/codicons.ts
-- go to the above and then enter <c-v>u<unicode> and the symbold should appear
-- or go here and upload the font file: https://mathew-kurian.github.io/CharacterMap/
-- find more here: https://www.nerdfonts.com/cheat-sheet
--
return {
  kind = {
    -- Text = "󰉿",
    Text = "",
    Method = "m",
    Function = "󰊕",
    Constructor = "",
    -- Field = "",
    Field = "󰒿",
    Variable = "󰆧",
    -- Class = "󰌗",
    Class = "",
    Interface = "",
    -- Module = "",
    -- Module = "󰅩",
    Module = "",
    -- Property = "",
    Property = "",
    Unit = "",
    Value = "󰎠",
    -- Enum = "",
    Enum = "",
    -- Keyword = "󰉨",
    Keyword = "󰌋",
    -- Snippet = "",
    -- Snippet = "",
    Snippet = "",
    Color = "󰏘",
    File = "󰈙",
    Reference = "",
    Folder = "󰉋",
    -- EnumMember = "",
    EnumMember = "",
    -- Constant = "󰏿",
    Constant = "󰏿",
    -- Struct = "",
    Struct = "󰙅",
    -- Event = "",
    Event = "󰥕",
    Operator = "󰆕",
    -- TypeParameter = "󰊄",
    TypeParameter = "",
  },
  type = {
    Array = "󰅨",
    Number = "",
    String = "󰉿",
    Boolean = "󰔡",
    Object = "󰅩",
  },
  documents = {
    File = "",
    Files = "",
    SymlinkFile = "",
    Folder = "",
    OpenFolder = "",
    EmptyFolder = "",
    OpenEmptyFolder = "",
    SymlinkFolder = "",
  },
  git = {
    Unstaged = "",
    Staged = "󰄳",
    Unmerged = "",
    Renamed = "",
    Untracked = "U",
    Ignored = "◌",
    Add = "",
    Mod = "",
    Remove = "",
    Rename = "",
    Diff = "",
    Repo = "",
    Octoface = "",
    Branch = "",
  },
  ui = {
    ArrowClosed = "",
    ArrowOpen = "",
    FilledArrow = "󰐊",
    EnterArrow = "",
    Lock = "󰍁",
    Circle = "",
    BigCircle = "",
    BigUnfilledCircle = "",
    Square = "■",
    BoldClose = "",
    Close = "󰅖",
    NewFile = "",
    Search = "󰍉",
    Lightbulb = "󰌵",
    Project = "",
    Dashboard = "",
    History = "󰥔",
    Comment = "󰅺",
    Bug = "",
    Code = "",
    Telescope = "",
    Gear = "",
    Package = "",
    List = "",
    SignIn = "",
    SignOut = "",
    Check = "󰄬",
    BoldCheck = "",
    Fire = "",
    Note = "󰎞",
    BookMark = "",
    Pencil = "󰏫",
    -- ChevronRight = "",
    ChevronRight = ">",
    Table = "",
    Calendar = "",
    CloudDownload = "",
    TruncLeft = "",
    TruncRight = "",
    Separator = "▎",
    ThickSeparator = "▊",
    Tilde = "~",
    TestTube = "󰙨",
    ClockFast = "󰅒",
    Prompt = "",
  },
  diagnostics = {
    Error = "󰅚",
    Warning = "",
    FilledWarning = "",
    Info = "",
    Hint = "󰌶",
    Other = "󰗡"
  },
  misc = {
    Robot = "󰚩",
    Squirrel = "",
    Tag = "",
    Watch = "",
    Smiley = "󰞅",
    Package = "",
    CircuitBoard = "",
  },
  dashboard = {
    Folder = "",
    Find = "󰈞",
    File = "",
    Time = "󰄉",
    Text = "󰊄",
    Setting = "",
    Shell = "",
    Close = "󰔡",
    Quit = "󰅚",
  }
}
