-- User files setup
require("config.options")
require("config.mappings")
require("core.lazy")
require("core.lsp")
-- Lua config
require("plugins.autopairs")
require("plugins.blink-cmp")
require("plugins.bufferline")
require("plugins.colorizer")
require("plugins.comment")
require("plugins.conform")
require("plugins.cybu")
require("plugins.diffview")
require("plugins.fzflua")
require("plugins.gitsigns")
require("plugins.hlargs")
require("plugins.illuminate")
require("plugins.lualine")
require("plugins.mini-ai")
require("plugins.mini-surround")
require("plugins.nvim-tree")
require("plugins.pounce")
require("plugins.range-highlight")
require("plugins.render-markdown")
require("plugins.smart-splits")
require("plugins.snacks") -- import all snacks-*.lua files
require("plugins.tidy")
require("plugins.todo-comments")
require("plugins.treesitter-context")
require("plugins.treesitter-textobjects")
require("plugins.treesitter")
