-- User files setup
require("user.lazy")
require("user.options")
require("user.mappings")
-- Lua plugins
require("plugins.lsp")
require("plugins.alpha")
require("plugins.autopairs")
require("plugins.bbye")
require("plugins.bufferline")
require("plugins.cmp")
require("plugins.colorizer")
require("plugins.comment")
require("plugins.cybu")
require("plugins.diffview")
require("plugins.dressing")
require("plugins.glow")
require("plugins.gitsigns")
require("plugins.highlight-undo")
require("plugins.hlargs")
require("plugins.hop")
require("plugins.illuminate")
require("plugins.indent-blankline")
require("plugins.lualine")
require("plugins.neogen")
-- require("plugins.neoscroll")
require("plugins.nvim-surround")
require("plugins.nvim-tree")
require("plugins.pounce")
require("plugins.range-highlight")
require("plugins.telescope")
require("plugins.tidy")
require("plugins.toggleterm")
require("plugins.treesitter-context")
require("plugins.treesitter")
require("plugins.trouble")
-- require("plugins.zen-mode")
require("plugins.todo-comments")
